Repository AY2021S1-CS2113T-F14-1/tp, pull requests merged in 2020-10, with the labels that each got.

#25 Implement Parser, UI, Command and other backend features
  src/main/java/seedu/duke/Command.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/backend/Parser.java
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/backend/UserInput.java
  src/main/java/seedu/duke/others/CommandBye.java
  src/main/java/seedu/duke/others/CommandHelp.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#27 John DukeException
  src/main/java/seedu/duke/DukeArgumentException.java
  src/main/java/seedu/duke/DukeException.java
  src/main/java/seedu/duke/DukeNoMatchException.java
  src/main/java/seedu/duke/backend/Ui.java
Labels: priority.High, severity.High, type.Bug

#33 Wang Zixin Finance version1.0
  docs/AboutUs.md
  src/main/java/seedu/duke/Finance/CommandFinanceAdd.java
  src/main/java/seedu/duke/Finance/CommandFinanceDel.java
  src/main/java/seedu/duke/Finance/CommandFinanceSummary.java
  src/main/java/seedu/duke/Finance/FinanceList.java
  src/main/java/seedu/duke/Finance/FinanceLog.java
  src/main/java/seedu/duke/backend/Parser.java
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/hr/MemberList.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High

#36 Implement JUnit Tests for Parser
  src/main/java/seedu/duke/backend/Parser.java
  src/test/java/seedu/duke/DukeTest.java
Labels: priority.High, severity.Medium, type.Bug

#42 Yutong hr ver0.2
  src/main/java/seedu/duke/DukeMemberListEmptyException.java
  src/main/java/seedu/duke/DukeMemberNotFoundException.java
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/MemberList.java
  src/test/java/seedu/duke/HrTest.java
Labels: type.Task

#44 FileManager
  .gitignore
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/DukeFileFormatException.java
  src/main/java/seedu/duke/DukeFileHeaderException.java
  src/main/java/seedu/duke/backend/FileManager.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/Member.java
  src/test/java/seedu/duke/DukeTest.java
  src/test/java/seedu/duke/FileManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story, type.Task

#53 Shorthand Commands
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/event/CommandEventAdd.java
  src/main/java/seedu/duke/event/CommandEventDel.java
  src/main/java/seedu/duke/event/CommandEventList.java
  src/main/java/seedu/duke/finance/CommandFinanceAdd.java
  src/main/java/seedu/duke/finance/CommandFinanceDel.java
  src/main/java/seedu/duke/finance/CommandFinanceSummary.java
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/CommandDelMember.java
  src/main/java/seedu/duke/hr/CommandViewMember.java
Labels: priority.Medium, type.Enhancement

#57 Yutong hr fixed bug
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/CommandDelMember.java
  src/main/java/seedu/duke/hr/Email.java
  src/main/java/seedu/duke/hr/Member.java
  src/main/java/seedu/duke/hr/MemberList.java
  src/main/java/seedu/duke/hr/Name.java
  src/main/java/seedu/duke/hr/Phone.java
Labels: type.Bug

#59 hr version 2.0
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/hr/CommandListConnection.java
  src/main/java/seedu/duke/hr/CommandListProfSpeaker.java
  src/main/java/seedu/duke/hr/CommandSearchMember.java
  src/main/java/seedu/duke/hr/CommandViewMember.java
  src/main/java/seedu/duke/hr/MemberList.java
Labels: priority.Medium

#64 Fixed bug in shorthand command
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/event/CommandEventList.java
  src/main/java/seedu/duke/event/EventList.java
  src/main/java/seedu/duke/finance/CommandFinanceDel.java
  src/main/java/seedu/duke/hr/CommandSearchMember.java
Labels: type.Bug

#67 Yutong prevents same name from being added again
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/MemberList.java
Labels: priority.Medium, type.Bug

#70 Yutong Update DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/hrDiagram/2.1S1.puml
  docs/hrDiagram/2.1S2.puml
  docs/hrDiagram/2.1S3.puml
  docs/hrDiagram/2.2S1.puml
  docs/hrDiagram/styleHR.puml
  docs/hrDiagramPic/2-1S1.png
  docs/hrDiagramPic/2-1S2.png
  docs/hrDiagramPic/2-1S3.png
  docs/hrDiagramPic/2-2S1.png
Labels: type.Task

#69 FileImport initial draft
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/Command.java
  src/main/java/seedu/duke/backend/FileManager.java
  src/main/java/seedu/duke/others/CommandImportCsv.java
Labels: priority.Medium, type.Enhancement, type.Story

#73 Yutong UGDG
  docs/UserGuide.md
  docs/hrDiagram/2.1S1.puml
  docs/hrDiagram/2.1S2.puml
  docs/hrDiagram/2.1S3.puml
  docs/hrDiagramPic/2-1S1.png
  docs/hrDiagramPic/2-1S2.png
  docs/hrDiagramPic/2-1S3.png
  src/test/java/seedu/duke/hr/HrTest.java
Labels: type.Task

#82 CSV Import Implementation
  src/main/java/seedu/duke/backend/Parser.java
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/others/CommandImportCsv.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.Medium, type.Enhancement, type.Story

#87 Yutong add event participants
  hs_err_pid28664.log
  replay_pid28664.log
  src/main/java/seedu/duke/backend/FileManager.java
  src/main/java/seedu/duke/backend/Parser.java
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/event/CommandAddEventAttendance.java
  src/main/java/seedu/duke/event/CommandDelEventAttendance.java
  src/main/java/seedu/duke/event/CommandViewEventAttendance.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/EventList.java
  src/main/java/seedu/duke/hr/CommandAddMember.java
  src/main/java/seedu/duke/hr/Member.java
  src/main/java/seedu/duke/hr/MemberList.java
  src/test/java/seedu/duke/hr/HrTest.java
Labels: priority.Medium, type.Story

#88 Add the change feature for user to change the information of a particular finance log
  src/main/java/seedu/duke/backend/Ui.java
  src/main/java/seedu/duke/finance/CommandFinanceChange.java
  src/main/java/seedu/duke/finance/FinanceList.java
  src/main/java/seedu/duke/finance/FinanceLog.java
  src/test/java/seedu/duke/finance/FinanceTest.java
Labels: priority.Medium

#90 Yutong del event participant
  src/main/java/seedu/duke/event/CommandAddEventAttendance.java
  src/main/java/seedu/duke/event/CommandDelEventAttendance.java
  src/main/java/seedu/duke/event/CommandViewEventAttendance.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/EventList.java
  src/main/java/seedu/duke/hr/MemberList.java
Labels: priority.Medium, type.Story

#95 Yutong attendance rate
  src/main/java/seedu/duke/hr/Member.java
  src/main/java/seedu/duke/hr/MemberList.java
  src/test/java/seedu/duke/hr/HrTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Story

#102 Yutong UserGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/userGuidePic/eventAddAttendanceCommand.PNG
  docs/userGuidePic/eventDeleteAttendanceCommand.PNG
  docs/userGuidePic/eventListAttendanceCommand.PNG
  docs/userGuidePic/hrAddMemberCommand.PNG
  docs/userGuidePic/hrChangeInfoCommand.PNG
  docs/userGuidePic/hrDelMemberCommand.PNG
  docs/userGuidePic/hrListMemberCommand.PNG
Labels: type.Task

#105 Yutong Hr DG
  HrArchitecture.png
  docs/DeveloperGuide.md
  docs/hrDiagram/CommandAddMember.puml
  docs/hrDiagram/CommandChangeMemberInfo.puml
  docs/hrDiagram/CommandDelMember.puml
  docs/hrDiagram/CommandViewMember.puml
  docs/hrDiagram/HrArchitecture.puml
  docs/hrDiagramPic/CommandAddMember.png
  docs/hrDiagramPic/CommandChangeMemberInfo.png
  docs/hrDiagramPic/CommandDelMember.png
  docs/hrDiagramPic/CommandViewMember.png
  docs/hrDiagramPic/HrArchitecture.png
Labels: type.Story

#106 Yutong DG update sequential diagram
  docs/DeveloperGuide.md
  docs/EventDiagram/6Step1.png
  docs/EventDiagram/6Step1.puml
  docs/EventDiagram/6Step2.png
  docs/EventDiagram/6Step2.puml
  docs/EventDiagram/6Step3.png
  docs/EventDiagram/6Step3.puml
  docs/EventDiagram/6Step4.png
  docs/EventDiagram/6Step4.puml
  docs/EventDiagram/7Step1.png
  docs/EventDiagram/7Step1.puml
  docs/EventDiagram/7Step2.png
  docs/EventDiagram/7Step2.puml
  docs/EventDiagram/7Step3.png
  docs/EventDiagram/7Step3.puml
  docs/EventDiagram/SequenceDiagram/CommandAddEventAttendance.png
  docs/EventDiagram/SequenceDiagram/CommandAddEventAttendance.puml
  docs/EventDiagram/SequenceDiagram/CommandDelEventAttendance.png
  docs/EventDiagram/SequenceDiagram/CommandDelEventAttendance.puml
  docs/EventDiagram/SequenceDiagram/CommandViewEventAttendance.png
  docs/EventDiagram/SequenceDiagram/CommandViewEventAttendance.puml
  src/main/java/seedu/duke/event/EventList.java
Labels: type.Task

#107 Yutong DG update
  docs/hrDiagram/CommandAddMember.puml
  docs/hrDiagram/CommandChangeMemberInfo.puml
  docs/hrDiagram/CommandDelMember.puml
  docs/hrDiagram/CommandViewMember.puml
  docs/hrDiagramPic/CommandAddMember.png
  docs/hrDiagramPic/CommandChangeMemberInfo.png
  docs/hrDiagramPic/CommandDelMember.png
  docs/hrDiagramPic/CommandViewMember.png
Labels: type.Task

#134 Fixed bug in event
  docs/UserGuide.md
  src/main/java/seedu/duke/event/CommandEventAdd.java
  src/main/java/seedu/duke/event/Event.java
  src/main/java/seedu/duke/event/EventList.java
  src/main/java/seedu/duke/others/CommandHelp.java
  src/test/java/seedu/duke/event/EventListTest.java
Labels: type.Bug
